-- This file is automatically generated by a matlab script 
--
-- Do not modify directly!
--

library ieee;
use ieee.std_logic_1164.all;
use IEEE.STD_LOGIC_arith.all;
use IEEE.STD_LOGIC_signed.all;
use work.sound_p.all;

package triangle_lut_pkg is

type lut_type is array(0 to 2**(PHASE_WIDTH-2)-1) of std_logic_vector(AMPL_WIDTH-1 downto 0);

	constant triangle_lut : lut_type := (
    conv_std_logic_vector(0,AMPL_WIDTH),
    conv_std_logic_vector(2,AMPL_WIDTH),
    conv_std_logic_vector(4,AMPL_WIDTH),
    conv_std_logic_vector(6,AMPL_WIDTH),
    conv_std_logic_vector(8,AMPL_WIDTH),
    conv_std_logic_vector(10,AMPL_WIDTH),
    conv_std_logic_vector(12,AMPL_WIDTH),
    conv_std_logic_vector(14,AMPL_WIDTH),
    conv_std_logic_vector(16,AMPL_WIDTH),
    conv_std_logic_vector(18,AMPL_WIDTH),
    conv_std_logic_vector(20,AMPL_WIDTH),
    conv_std_logic_vector(22,AMPL_WIDTH),
    conv_std_logic_vector(24,AMPL_WIDTH),
    conv_std_logic_vector(26,AMPL_WIDTH),
    conv_std_logic_vector(28,AMPL_WIDTH),
    conv_std_logic_vector(30,AMPL_WIDTH),
    conv_std_logic_vector(32,AMPL_WIDTH),
    conv_std_logic_vector(34,AMPL_WIDTH),
    conv_std_logic_vector(36,AMPL_WIDTH),
    conv_std_logic_vector(38,AMPL_WIDTH),
    conv_std_logic_vector(40,AMPL_WIDTH),
    conv_std_logic_vector(42,AMPL_WIDTH),
    conv_std_logic_vector(44,AMPL_WIDTH),
    conv_std_logic_vector(46,AMPL_WIDTH),
    conv_std_logic_vector(48,AMPL_WIDTH),
    conv_std_logic_vector(50,AMPL_WIDTH),
    conv_std_logic_vector(52,AMPL_WIDTH),
    conv_std_logic_vector(54,AMPL_WIDTH),
    conv_std_logic_vector(56,AMPL_WIDTH),
    conv_std_logic_vector(58,AMPL_WIDTH),
    conv_std_logic_vector(60,AMPL_WIDTH),
    conv_std_logic_vector(62,AMPL_WIDTH),
    conv_std_logic_vector(64,AMPL_WIDTH),
    conv_std_logic_vector(68,AMPL_WIDTH),
    conv_std_logic_vector(70,AMPL_WIDTH),
    conv_std_logic_vector(72,AMPL_WIDTH),
    conv_std_logic_vector(74,AMPL_WIDTH),
    conv_std_logic_vector(76,AMPL_WIDTH),
    conv_std_logic_vector(78,AMPL_WIDTH),
    conv_std_logic_vector(80,AMPL_WIDTH),
    conv_std_logic_vector(82,AMPL_WIDTH),
    conv_std_logic_vector(84,AMPL_WIDTH),
    conv_std_logic_vector(86,AMPL_WIDTH),
    conv_std_logic_vector(88,AMPL_WIDTH),
    conv_std_logic_vector(90,AMPL_WIDTH),
    conv_std_logic_vector(92,AMPL_WIDTH),
    conv_std_logic_vector(94,AMPL_WIDTH),
    conv_std_logic_vector(96,AMPL_WIDTH),
    conv_std_logic_vector(98,AMPL_WIDTH),
    conv_std_logic_vector(100,AMPL_WIDTH),
    conv_std_logic_vector(102,AMPL_WIDTH),
    conv_std_logic_vector(104,AMPL_WIDTH),
    conv_std_logic_vector(106,AMPL_WIDTH),
    conv_std_logic_vector(108,AMPL_WIDTH),
    conv_std_logic_vector(110,AMPL_WIDTH),
    conv_std_logic_vector(112,AMPL_WIDTH),
    conv_std_logic_vector(114,AMPL_WIDTH),
    conv_std_logic_vector(116,AMPL_WIDTH),
    conv_std_logic_vector(118,AMPL_WIDTH),
    conv_std_logic_vector(120,AMPL_WIDTH),
    conv_std_logic_vector(122,AMPL_WIDTH),
    conv_std_logic_vector(124,AMPL_WIDTH),
    conv_std_logic_vector(126,AMPL_WIDTH),
    conv_std_logic_vector(127,AMPL_WIDTH)
	);

end triangle_lut_pkg;

package body sine_lut_pkg is
end sine_lut_pkg;