#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun May 17 14:17:45 CEST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 839af8cf95c04b7684a57be431689ec7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ControlMenuTB_behav xil_defaultlib.ControlMenuTB -log elaborate.log"
xelab -wto 839af8cf95c04b7684a57be431689ec7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ControlMenuTB_behav xil_defaultlib.ControlMenuTB -log elaborate.log

