# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/ise/pong_reference/pong_reference.cache/wt [current_project]
set_property parent.project_path /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/ise/pong_reference/pong_reference.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_output_repo /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/ise/pong_reference/pong_reference.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/note_duration_fsm.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/melodies/melody_pkg.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/dds_synthesizer/sine_lut_8_x_16.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/address_counter.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/tuningtable/stimmung_lut_6_x_32.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/melodies/melody_table.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/dds_synthesizer/dds_synthesizer.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/address_generator.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/note_generator.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/volume_control/vol_ctrl.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/tuningtable/tuning_table.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/MMcodec01/mmCodec_initial.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/MMcodec01/mmCodec01_dac_int.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/MMcodec01/frequenz_div.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/MMcodec01/cntrl_int_neu.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/dds_synthesizer/dds.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/melody_player.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/MMcodec01/MMcodec01.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/MMcodec01/audio_clk_gen.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/applied_components/melodies/melody_pong.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/score_display/src/seven_seg_dec.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/score_display/src/score_counter.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/score_display/src/bin_to_bcd_dec.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/rotary_encoder/src/rot_enc_decoder.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/rotary_encoder/src/debounce.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/vga_controller/src/vga_controller.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/sound_interface/sound_interface.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/score_display/src/score_display.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/rotary_encoder/src/controller_interface.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/collision_detection/src/collision_detection.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/clock_enable.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/ball_motion/src/ball_motion.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/src/pong_toplevel.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/ise/pong_reference/pong_reference.srcs/sources_1/imports/SourceFiles/sine_lut_8_x_8.vhd
  /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/ise/pong_reference/pong_reference.srcs/sources_1/imports/SourceFiles/PWM_Modulator.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/ise/pong_reference/pong_reference.srcs/constrs_1/imports/pong_reference.src/Pynq_constraint_file.xdc
set_property used_in_implementation false [get_files /media/hardieck/hardieck-floyd/Work/repositorien/vhdlkurs/PYNQ-Projekte/PYNQ-Pong/pong_reference/ise/pong_reference/pong_reference.srcs/constrs_1/imports/pong_reference.src/Pynq_constraint_file.xdc]


synth_design -top pong_top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pong_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pong_top_utilization_synth.rpt -pb pong_top_utilization_synth.pb"
