--------------------------------------------------------------------------------
-- Title          : Pong Toplevel
-- Filename       : toplevel_pong.vhd
-- Project        : 6. Uebungsblatt VHDL-Kurs (Pong-Spiel)
--------------------------------------------------------------------------------
-- Author         : Michael Kunz
-- Company        : Universitaet Kassel, FG Digitaltechnik
-- Date           : 21.06.2010
-- Language       : VHDL93
-- Synthesis      : No
-- Target Family  : ALL
-- Test Status    : !!! not released !!!
--------------------------------------------------------------------------------
-- Applicable Documents:
-- 
--
--------------------------------------------------------------------------------
-- Revision History:
-- Date        Version  Author   Description
-- 21.06.2010  1.0      MK       Created
-- 27.08.2013  1.1		MK		 MMCodec01 & Eliminating Component Declaration
-- 20.05.2019  1.2      MH       Convert to PYNQ-Board useage
-- 14.06.2020  1.3      BLK      Implementation of a new Sound-Interface
--------------------------------------------------------------------------------
-- Description:
--
-- Dieses Modul stellt die Toplevel-Domaene fuer das Pong-Spiel dar, welches
-- von den Studierenden des VHDL-Kurses entwickelt werden soll. 
--
-- Es verbindet das Visualisierungsmodul mit dem Modul zur Ballbewegung und
-- Kollisionserkennung. Die fehlenden Eingaben der Module zur Schläegerbewegung
-- werden hier exemplarisch (testweise) gesetzt.

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_unsigned.all;
use IEEE.STD_LOGIC_ARITH.all;
 
ENTITY pong_top IS
	generic(
		game_enable_clocks: integer := 2100000); -- Propox version 840000
	port( 
		clock : in std_logic;
		reset : in std_logic;
		
		-- Play Modus Selector (Shield-Switches on the right)
		slide_sw_i : in std_logic_vector(1 downto 0);
				
		pmod_c : in std_logic_vector(7 downto 0);
		blue_led : out std_logic_vector(7 downto 0);
		
		-- Controller Interface
		--rot_enc1_i 							: in  std_logic_vector(1 downto 0);
		--push_button1_i 					    : in  std_logic;
		
		--rot_enc2_i 							: in  std_logic_vector(1 downto 0);
		--push_button2_i 					    : in  std_logic;
		  
		-- Sound Interface
		aud_pwm_o : out std_logic;
		aud_sd_o  : out std_logic;

		-- Seven Segment Display
		ssd_data : out std_logic_vector(7 downto 0);
		ssd_enable : out std_logic_vector(7 downto 0);

		-- VGA Controller
		VGA_HS, VGA_VS : out  std_logic;
		VGA_R, VGA_G, VGA_B	: out  std_logic_vector (3 downto 0);

		-- leds
		--;nled_o         		 	: out  std_logic_vector (7 downto 0)
		led : out std_logic_vector(3 downto 0)
		);

END pong_top;
 
ARCHITECTURE behavior OF pong_top IS 
   
	signal racket_y_pos1, racket_y_pos1_player : std_logic_vector(9 downto 0);
	signal racket_y_pos2, racket_y_pos2_player : std_logic_vector(9 downto 0);
	signal ball_x : std_logic_vector(9 downto 0);
	signal ball_y : std_logic_vector(9 downto 0);
	signal hit_wall : std_logic_vector(2 downto 0);
	signal hit_racket_l : std_logic_vector(1 downto 0);
	signal hit_racket_r : std_logic_vector(1 downto 0);
	signal game_over	: std_logic;
	signal push_but_deb1, push_but_deb2 : std_logic;
	signal Npush_but_deb1, Npush_but_deb2 : std_logic;
	signal seven_seg_leds : std_logic_vector(6 downto 0);
	signal seven_seg_sel : std_logic_vector(5 downto 0);

	signal nreset : std_logic;
	signal game_enable : std_logic;
	signal vga_enable : std_logic;
--	signal note_enable : std_logic; Signal generated by the Sound-Interface itself.
--	signal dds_enable : std_logic;  Signal generated by the Sound-Interface itself.
	signal led_enable : std_logic; 
	signal nslide_sw : std_logic_vector(1 downto 0);

	signal leds : std_logic_vector (3 downto 0);
	
	signal nseven_seg_leds_o : std_logic_vector(6 downto 0);
	signal nseven_seg_sel_o  : std_logic_vector(5 downto 0);
	
	signal h_sync_o : std_logic;
	signal v_sync_o : std_logic;
    signal red_o : std_logic_vector   (2 downto 0);
    signal green_o : std_logic_vector (2 downto 0);
    signal blue_o : std_logic_vector  (2 downto 0);
    
--  Signals for the old Sound-Interface:
--    signal lrcout_o :  std_logic;
--    signal bclk_o   :  std_logic;
--    signal sclk_o   :  std_logic;
--    signal din_i    :  std_logic;
--    signal dout_o   :  std_logic;
--    signal sdout_o  :  std_logic;
--    signal ncs_o    :  std_logic;
--    signal mck_o    :  std_logic;
--    signal mode_o   :  std_logic;
    
    signal rot_enc1_i     : std_logic_vector(1 downto 0);
    signal push_button1_i : std_logic;
    
    signal rot_enc2_i     : std_logic_vector(1 downto 0);
    signal push_button2_i : std_logic;        

BEGIN

ssd_data(7 downto 1)   <= nseven_seg_leds_o;
ssd_data(0)            <= '1';
ssd_enable(6 downto 1) <= nseven_seg_sel_o;
ssd_enable(7)          <= '1';
ssd_enable(0)          <= '1';

VGA_HS <= h_sync_o;
VGA_VS <= v_sync_o;

--blue_led <= not pmod_c;

rot_enc1_i <= pmod_c(7 downto 6);
push_button1_i <= not pmod_c(5);

rot_enc2_i <= pmod_c(3 downto 2);
push_button2_i <= not pmod_c(1);



--led(0) <= push_button1_i;
--led(1) <= push_button2_i;
--led(2) <= '0'; 
--led(3) <= '0';

	clk_enable: entity work.clock_enable 
		generic map(
			game_enable_clocks => game_enable_clocks)
		port map (
			clock 	    	=> clock,
			reset 			=> reset,
			vga_enable_o 	=> vga_enable,
			game_enable_o	=> game_enable,
			led_enable_o	=> led_enable,
			note_enable_o	=> open, -- At the moment the Sound-Interface has it's own enable-signal generator and requires only the system clock.
			dds_enable_o	=> open  -- An implementation of this generator can be found in the Sound-Interface.
			);
	
	controller_interface1 : entity work.controller_interface
		generic map(
			clk_frequency_in_Hz => 125E6, -- Propox version 50E6
			debounce_time_in_us => 2000,
			racket_height 	    => 60,
			racket_steps 	    => 10,
			screen_height	    => 480)
		port map(
			clock_i				=> clock,	
			reset_i				=> reset,
			rot_enc_i			=> rot_enc1_i,
			push_but_i		    => push_button1_i,
			push_but_deb_o      => push_but_deb1,
			racket_y_pos_o      => racket_y_pos1_player
			);
	
	controller_interface2 : entity work.controller_interface
		generic map(
			clk_frequency_in_Hz => 125E6,
			debounce_time_in_us => 2000,
			racket_height 		=> 60,
			racket_steps		=> 10,
			screen_height		=> 480)
		port map(
			clock_i		        => clock,	
			reset_i	            => reset,
			rot_enc_i 	        => rot_enc2_i,
			push_but_i 	        => push_button2_i,
			push_but_deb_o      => push_but_deb2,
			racket_y_pos_o      => racket_y_pos2_player
			);


	collision: entity work.collision_detection
		generic map(
			ball_length         => 6,
			racket_length		=> 10,
			racket_height		=> 60,
			racket_left_space	=> 20,
			racket_right_space 	=> 610,
			screen_height 		=> 480)
		port map(
			clock_i 			=> clock,
			reset_i 			=> reset,
			racket_y_pos1_i     => racket_y_pos1,
			racket_y_pos2_i     => racket_y_pos2,
			ball_x_i 		 	=> ball_x,
			ball_y_i 			=> ball_y,
			hit_wall_o 		 	=> hit_wall,
			hit_racket_l_o 	    => hit_racket_l,
			hit_racket_r_o 	    => hit_racket_r
			);


	motion: entity work.ball_motion
		generic map(
			ball_length			=> 6,
			racket_length		=> 10,
			racket_height		=> 60,
			racket_left_space	=> 20,
			racket_right_space 	=> 610,
			screen_height 		=> 480,
			speedup_racket		=> 100)
		port map(
			clock_i 			=> clock,
			reset_i 			=> reset,
			game_enable_i		=> game_enable,
			push_but1_deb_i	    => Npush_but_deb1,
			push_but2_deb_i     => Npush_but_deb2,
			game_over_i			=> game_over,
			hit_wall_i 		 	=> hit_wall,
			hit_racket_l_i 	    => hit_racket_l,
			hit_racket_r_i 	    => hit_racket_r,
			ball_x_o 			=> ball_x,
			ball_y_o 			=> ball_y
			);
 
	visualization: entity work.vga_controller
		generic map(
			ball_length				=>  6,
			racket_length			=>  10,
			racket_height			=>  60,
			racket_left_space	    =>  20,
			racket_right_space      =>  610,
			H_max					=>  799,
			V_max					=>  524)
		port map(
			clock_i 				=> clock,
			reset_i 				=> reset,
			vga_enable_i 		    => vga_enable,
			racket_y_pos1_i         => racket_y_pos1,
			racket_y_pos2_i         => racket_y_pos2,
			ball_x_i 				=> ball_x,
			ball_y_i 				=> ball_y,
			h_sync_o 				=> h_sync_o,
			v_sync_o 				=> v_sync_o,
			red_o 					=> VGA_R,
			green_o 				=> VGA_G,
			blue_o 					=> VGA_B
			);
	
	
	sound : entity work.SoundInterface
	port map ( clock_i         => clock,
               reset_i         => reset,
            -- Inputs 
               hit_wall_i      => hit_wall,
               hit_racket_l_i  => hit_racket_l,
               hit_racket_r_i  => hit_racket_r,
               game_over_i     => game_over,
               push_but1_deb_i => Npush_but_deb1,
               push_but2_deb_i => Npush_but_deb2,
               debug_o         => open,   -- Debug Output: States of the Controll FSM
               deb_clr_o       => open,   -- Debug Output: Clear signals at the end of each sound sample.
           -- Outputs
               audio_pwm_o     => aud_pwm_o,
               audio_sd_o      => aud_sd_o);

	score_display_inst : entity work.score_display
		generic map(score_max => 15)
		port map(clock_i          => clock,
			     reset_i		  => reset,
			     hit_wall_i 	  => hit_wall,
                 led_enable_i 	  => led_enable,
                 push_but1_deb_i  => Npush_but_deb1,
                 push_but2_deb_i  => Npush_but_deb2,
                 seven_seg_leds_o => seven_seg_leds,
                 seven_seg_sel_o  => seven_seg_sel,
                 count_1_o        => open, -- Debug Output of the game counter 1 in binary
                 count_2_o        => open, -- Debug Output of the game counter 2 in binary
                 game_over_o      => game_over);
	
	nseven_seg_leds_o <= not seven_seg_leds;
	nseven_seg_sel_o <= not seven_seg_sel;
	nslide_sw <= not slide_sw_i;

with nslide_sw(1) select
	racket_y_pos1 <= 	ball_y-14 when '1',	
	                    racket_y_pos1_player when others;

with nslide_sw(0) select
	racket_y_pos2 <= 	ball_y-14 when '1', 
	                    racket_y_pos2_player when others;

	nreset <= reset; -- Propox version : nreset <= not reset;
	Npush_but_deb1 <= not push_but_deb1;
	Npush_but_deb2 <= not push_but_deb2;

END;
